### ISSUE TITLE
Script names

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo-bridge-py#15]
There's no escaping the naming question!

Currently, this repo installs scripts called `krbb_glimpse`, `krbb_monitor` and `krbb_server_sim`.

At a minimum I'd like to change the underscores to dashes, which are more conventional in commands.

The `krbb-` prefix also feels a bit awkward, but I don't really have a better alternative to propose at the moment.

**Comment by tmichela** [comment]
Agreed, but I like short identifiable names, most of these scripts might also just disappear at some point (debug tools for me...)

**Comment by takluyver** [comment]
Hans suggested spelling out `karabo-bridge-` in full, with the rationale that clarity is better than brevity, and we can tab-complete it anyway.
