### ISSUE TITLE
byte data

### ISSUE THREAD

**Issue by zhujun98** [European-XFEL/karabo-bridge-py#24]
The use of something like "bytes(np.ones(16, dtype=np.uint8))" in the new simulator does not resemble what comes from the bridge. "bytes(np.ones(16, dtype=np.uint8))" is packed as MSGPACK_OBJECT_BIN while np.ones(16, dtype=np.uint8) is packed as MSGPACK_OBJECT_ARRAY. When I test my code with karabo devices (LimaSimultedCamera and PipeToZeroMQ), the small arrays (in the second message following the first one with content = "msgpack") are all packed as MSGPACK_OBJECT_ARRAY.

It is also recommended to use MSGPACK_OBJECT_ARRAY as packed small array data since data type information is also encoded. There is no way to know the data type from MSGPACK_OBJECT_BIN without a header file.

**Comment by tmichela** [comment]
I only reflect here the data type we get from the real system at the moment.
