### ISSUE TITLE
Time for request data quadruples

### ISSUE THREAD

**Issue by zhujun98** [European-XFEL/karabo-bridge-py#30]
The time for my cpp client to finish the function call "next()" quadruples with the new master branch.

**Comment by tmichela** [comment]
you mean getting data from the simulation?

**Comment by zhujun98** [comment]
Yes, I mean getting data from the simulation.

**Comment by takluyver** [comment]
@tmichela's changes to the simulation code in #42 (just merged) include an option to skip generating the random data, which probably makes it quicker. This is `--gen zeros` at the command line.

**Comment by zhujun98** [comment]
Thank you for letting me know! I tried it but my cpp client test failed (even without --gen zeros). Maybe something (e.g. name of a key) has been changed and I need to check. Indeed, for the integration test of cpp client, I prefer data with none-zero numbers since a chunk of zeros could also mean reading from some other memory space.

**Comment by takluyver** [comment]
Changes in #44 made this quicker again, hopefully back to a level comparable to what we had before. There's also an option to simulate a single detector module, which is quicker because it involves less data.
