### ISSUE TITLE
Key error when streaming data live

### ISSUE THREAD

**Issue by skuschel** [European-XFEL/karabo-bridge-py#50]
We're running into a problem streaming the data from a camera in the live stream. 
```
host='tcp://10.253.0.142:6666'
type='REQ'
c=Client(host,type)
data=c.next()
data['SQS_DPU_LIC/CAM/YAG_UPSTR:daqOutput']['data.image.pixels']  
```
the last line returns a key error.

However, the same data dictionary when streaming a recorded H5 file returns the detector image.

Any advice?

**Comment by tmichela** [comment]
The data available in stream does not contains all of the data stored in files. The configuration is specific to each instrument (and each experiment). I would advise to ask your contact person at the SQS instrument to find out what is available and to request additional data sources if what you need isn't already available in the data stream.

One easy way to get an overview of the data available from a bridge is to use the `karabo-bridge-glimpse` command (available in if you use our provided enviromnent with `module load exfel exfel_anaconda3` or if you install the python `karabo-bridge` package in your environment):
```bash
karabo-bridge-glimpse tcp://10.253.0.142:6666
```
This will show you all data sources available and the associated keys.

**Comment by skuschel** [comment]
Thanks you very much!
