### ISSUE TITLE
Karabo-bridge-glimpse ZMQ error when using bash

### ISSUE THREAD

**Issue by skuschel** [European-XFEL/karabo-bridge-py#51]
I am currently using the `karabo-bridge-glimpse` at SQS to dignose errors in the datastream. Whenever I use it in the default shell it works. However, I like to work in the bash and when I start the bridge in from the bash I get a ZMQ error. Here is how to reporduce it:

1) in default shell (this works as expected). After logging onto exflonc35:
```
module load anaconda3/5.2
karabo-bridge-glimpse tcp:10.253.142:6666
```

2) does not work. After looging onto exflonc35:
```
bash
module load anaconda3/5.2
karabo-bridge-glimpse tcp:10.253.142:6666
```
This yield the following error message: 
```
Traceback (most recent call last):
  File "/software/anaconda3/5.2/bin/karabo-bridge-glimpse", line 11, in <module>
    sys.exit(main())
  File "/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_bridge/cli/glimpse.py", line 184, in main
    client = Client(args.endpoint)
  File "/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_bridge/client.py", line 60, in __init__
    self._socket.connect(endpoint)
  File "zmq/backend/cython/socket.pyx", line 580, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Protocol not supported
```
I did not create my own python installation, and `whereis karabo-bridge-glimpse` points to the same executable in both cases. 

Its probably a low priority, but I wanted to make you aware that there is something in the environment. Strangely, my own python scripts, which are using the `karabo-bridge.Client` to connect to the live stream work in both shells. 

Cheers
Stephan

**Comment by takluyver** [comment]
Normally the endpoint specification has a `//` in, like `tcp://10.253.142:6666`. Does that make a difference?

**Comment by skuschel** [comment]
That was a typo, I actually used `tcp://10.253.142:6666` in both instances.

However, I just double checked my configuration and figured that I a old `.bashrc`, as the live servers are using a different home than the maxwell server and I updated it in only in one place. Sorry for bothering you and thank you very much for your fast response!
