### ISSUE TITLE
Glimpse and monitor commands are hardcoded to req-rep pattern

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo-bridge-py#55]
It should be possible to use them with whatever pattern the server is using - whether they take an option for the pattern, or autodetect it.

**Comment by takluyver** [comment]
Possible downside of autodetection: trying one pattern after another, with enough delay to receive a big message, could make it harder to notice that e.g. you've just made a typo in the port number.

**Comment by tmichela** [comment]
fixed in #57
