### ISSUE TITLE
Duplicated url scheme

### ISSUE THREAD

**Issue by JunCEEE** [European-XFEL/karabo-bridge-py#62]
If run
`karabo-bridge-server-sim -d AGIPDModule -r 10255`
got
`tcp://tcp://max-exfl001.desy.de:10255`

Expected:
`tcp://max-exfl001.desy.de:10255`

Cheers,
Jun

**Comment by tmichela** [comment]
Hi @JunCEEE 

Thanks for the feedback. We actually had a fix already but it was never released.
I've now deployed [it](https://pypi.org/project/karabo-bridge/) in our environment on Maxwell (available with `module load exfel exfel_anaconda3`)
If you want to install and use it in your own environment you can with `pip install karabo-bridge>=0.6.1`
