### ISSUE TITLE
Option to transmit recorded data

### ISSUE THREAD

**Issue by FilipeMaia** [European-XFEL/karabo-bridge-py#63]
Feature request to add an option to read a previously recorded data file (.h5) and send if out through the bridge.

**Comment by FilipeMaia** [comment]
Hi @tmichela 

I was not aware. That's very useful!
Maybe you should point this out in the help or something.

Cheers,
Filipe

**Comment by takluyver** [comment]
Just to add, we also have an internal tool called karabo-bridge-recorder, which can capture the ZMQ messages and play them back in exactly the same format, for testing code with. We don't want anyone to use that to save scientific data, but if you want to capture some samples of bridge data purely for testing purposes, ping us on da-support@xfel.eu and we can help you work it out.

**Comment by tmichela** [comment]
Thanks for the feedback @FilipeMaia 

> Maybe you should point this out in the help or something.

Currently the documentation about the karabo bridge protocol is part of our general [EuXFEL data analysis documentation](https://in.xfel.eu/readthedocs/docs/data-analysis-user-documentation/en/latest/karabo_bridge/protocol.html) as it cover different packages.

And I agree it is not particularly user friendly to find information in that case. I planed to move the documentation here a while back (#59), I'll resume working on that part.
